---
title: "About me"
site: distill::distill_website
---

* PhD 2004, University of Otago

My name is not A. James Green, but James A. Green. Having a super common name
(Hi other person called [James A. Green](https://psych.uconn.edu/person/james-green/)
who is also a psychology PhD!!), I needed to find a unique handle, and 
theJamesGreen seemed a bit pretentious. So I'm just aJamesGreen, one of many!

<aside>The other James A. Green at the University of Connecticut is department chair — Not one of my ambitions — and an expert in infant crying. His first publication was around the year I was born</aside>

This page is not a CV, but more a narrative of my career so far.

## Careers as a garden of forking paths

Up until the end of my PhD, I had had a fairly linear path. And, after I submitted, I nearly landed a confirmation-path (tenure-track) job in the psychology department I trained in, which would have continued with an obvious linear path. I would have developed my own independent research agenda, but it would still have obviously lead on from my PhD. 

However, I didn't land that job, and so started applying elsewhere. I nearly^[I wouldn't say 'nearly' usually, but they only interviewed two candidates, and I was apparently appointable] ended up with a post-doc in Cardiff. In reflecting on the forking paths of academia, I've found it interesting that neither the successful candidate, nor the PI on the [project](https://doi.org/10.2190%2FAG.71.2.a) appear to still be in academia.

Instead, I ended up — after a fortuitous discussion at the photocopier — with a research role with [Geoff White](https://www.otago.ac.nz/psychology/staff/geoffwhite.html). The original scope for that role was mostly to be supporting a very strongly behaviourist project, but after some detour into prospective memory, I ended up doing lots of stuff on Sauvignon blanc. 

While in that post, I got a grant through to the second round of New Zealand's prestigious Marsden Fund. Had that been successful, I would have had three years as a co-PI of a $600,000+ project with a _wine_ budget ^[I'm actually really disappointed that the wine was goingt to be a very small part of the overall cost, only about \$10,000 or so], exploring the following: 

> Sensory science studies of aroma and flavour emphasise chemosensory properties of wine as the dominant source for judgments about wine quality. Smells and tastes are percepts that do not exist outside of the human observer, however, so an analysis of wine judgment that emphasises only chemosensory properties is incomplete. According to recent studies of the way that wine is perceived and judged, the sensory experience of wine is ambiguous and may be open to interpretation, with marked individual differences among even wine experts.  Therefore, wine memory and perception are likely to be predominantly influenced by processes of construction and interpretation. Further, wine drinking or tasting is typically a social experience, and the ambiguous nature of wine allows a powerful influence by social factors, which have not been explored. The novel question of our proposal is whether wine judgements are subject to memory illusions and social influence. We propose to apply some classic procedures that can reveal distortions in normal memory over time and the influence of social situations on perception, in order to demonstrate memory illusions and social contagion in wine judgements and memory. ^[This abstract has never been outside a rather small group of people!]





```