---
title: "Research"
description: |
  Health, methodology, education, wine, random.
---

# Health Psychology

I have been involved in a diverse array of both quantitative and qualitative projects involving medicines. 
. I explore decision-making about medicines, including adherence, preventive health behaviours, and how culture influences medicine taking behaviour and understanding. I examine communication between healthcare professionals, and between healthcare professionals and patients. 

# Methodology



# Education

I have a strong interest in **admissions** processes and predictors of academic success, initially as part of a role on a pharmacy admissions committee trying to increase the number of Maori students gain entry. I have reviewed a good number of papers in this area for *Medical Education* and *Advances in Health Sciences Education*.

* Green, J.A., (2015). The effect of English proficiency and ethnicity on academic performance and progress. Advances in Health Sciences Education, 20, 219-228. doi: 10.1007/s10459-014-9523-7  

I also have been involved in several **interprofessional education** projects, and currently teach an interprofessional cohort in allied health. 

For my *Master of Arts in Teaching Learning and Scholarship*, I've also been blending my interest in methods with education. I'm a long time teacher of research methods and/or statistics, mostly to postgraduate professional cohorts. My project, which will be highlighted here soon, is looking at **innovativion in research methods teaching**. 

# Wine

No longer such an active area for me [sadface], but through a long collaboration with Wendy Parr (Lincoln University, Marlborough Wine Research Centre) and a number of her French collaborators (Dominique Valentin and others), we demonstrated that wine experts have a clear cognitive prototypes that influence their perceptions. We have also delineated sensory and physicochemical differences between different national and sub-national wine regions for Sauvignon blanc.

The last project I worked on here was looking to see whether the position of the moon per the biodynamic calendar influenced perceptions of wine. It did not [mic drop]

* Parr, W. V., Valentin, D., Reedman, P., Grose, C., & Green, J. A. (2017). Expectation or Sensorial Reality? An Empirical Investigation of the Biodynamic Calendar for Wine Drinkers. PloS one, 12, e0169257. https://doi.org/10.1371/journal.pone.0169257 \doi{10.1371/journal.pone.0169257}

I narrowly missed a large scale Marsden Fund grant in this area in 2005, which had it been successful, might have led to me having a very different career!

# Random

My PhD (2004) was located at the intersection of social psychology and sociolinguistics, but even back then, I had rather broad interests. I've had an extended but peripheral involvement in evaluating different accents of English, for example. And have a stack of file-drawered studies on the reasons analysis effect — listing your reasons underlying a judgement messes with your judgement. One of these is published, showing a carryover effect from reasoning to subsequent judgements. 
